# Generated by Django 4.1.7 on 2023-03-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ankets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ankets',
            name='female',
        ),
        migrations.RemoveField(
            model_name='ankets',
            name='male',
        ),
        migrations.AddField(
            model_name='ankets',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], default='default', max_length=11),
            preserve_default=False,
        ),
    ]
