# Generated by Django 4.1.7 on 2023-03-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ankets_female_remove_ankets_male_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankets',
            name='gender',
            field=models.CharField(blank='False', choices=[('', 'Male'), ('0', 'Female')], max_length=11),
        ),
    ]
