# Generated by Django 4.1.7 on 2023-03-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ankets_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ankets',
            name='medical',
            field=models.CharField(blank='False', choices=[('0', 'Непереносимость глютена'), ('1', 'Непереносимость лактозы'), ('2', 'Диабет'), ('3', 'Язва'), ('4', 'Изжога'), ('5', 'Повышенный холестерин')], max_length=40),
        ),
    ]
