# Generated by Django 4.1.7 on 2023-03-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ankets_medical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ankets',
            name='medical',
        ),
        migrations.AddField(
            model_name='ankets',
            name='medical_1',
            field=models.BooleanField(default=False, verbose_name='Изжога'),
        ),
        migrations.AddField(
            model_name='ankets',
            name='medical_2',
            field=models.BooleanField(default=False, verbose_name='Непереносимость глютена'),
        ),
        migrations.AddField(
            model_name='ankets',
            name='medical_3',
            field=models.BooleanField(default=False, verbose_name='Непереносимость лактозы'),
        ),
    ]
