# Generated by Django 4.1.7 on 2023-05-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_ankets_name_ankets_breakfast_ankets_dinner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ankets',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
