# Generated by Django 4.1.7 on 2023-05-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_ankets_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankets',
            name='dinner',
            field=models.CharField(blank='False', choices=[('', 'Горячее блюдо с гарниром'), ('0', 'Салат'), ('1', 'Десерт')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ankets',
            name='lunch',
            field=models.CharField(blank='False', choices=[('', 'Суп'), ('0', 'Горячее блюдо с гарниром'), ('1', 'Салат')], max_length=100),
        ),
    ]
