# Generated by Django 4.1.7 on 2023-05-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_ankets_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('link', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('calories', models.IntegerField(verbose_name='Калории')),
                ('protein', models.IntegerField(verbose_name='Белки')),
                ('lipid', models.IntegerField(verbose_name='Жиры')),
                ('carbon', models.IntegerField(verbose_name='Углеводы')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
        ),
    ]
